# Generated by Django 5.2.17 on 2026-08-19 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('data_nascimento', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='usuario',
            name='perfil',
            field=models.CharField(choices=[('coordenador', 'Coordenador'), ('aluno', 'Aluno'), ('professor', 'Professor'), ('administrador', 'Administrador'), ('responsavel', 'Responsável')], max_length=20),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.CharField(max_length=100)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('ip', models.CharField(max_length=100)),
                ('resultado', models.CharField(max_length=100)),
                ('detalhes', models.TextField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Consentimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finalidade', models.CharField(max_length=100)),
                ('versao', models.CharField(max_length=10)),
                ('data_consentimento', models.DateField(auto_now_add=True)),
                ('revogado', models.BooleanField(default=False)),
                ('data_revogado', models.DateField(blank=True, null=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.aluno')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_original', models.CharField(max_length=255)),
                ('arquivo_criptografado', models.FileField(upload_to='documentos_criptografados/')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='pendente', max_length=20)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.aluno')),
                ('responsavel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Acesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio_acesso', models.DateTimeField()),
                ('fim_acesso', models.DateTimeField()),
                ('revogado', models.BooleanField(default=False)),
                ('data_revogado', models.DateTimeField(blank=True, null=True)),
                ('concedido_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concedido_por', to=settings.AUTH_USER_MODEL)),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('documento_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.documento')),
            ],
        ),
    ]
