# Generated by Django 5.2.17 on 2026-09-11 02:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='cpf',
        ),
        migrations.AddField(
            model_name='participante',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participante', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='perfil',
            field=models.CharField(choices=[('coordenador', 'Coordenador'), ('pesquisador', 'Pesquisador'), ('administrador', 'Administrador'), ('responsavel', 'Responsável'), ('participante', 'Participante')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='participacaopesquisa',
            constraint=models.UniqueConstraint(fields=('participante', 'pesquisa'), name='unique_participante_pesquisa'),
        ),
    ]
