# Generated by Django 5.2.17 on 2026-09-11 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DadoPesquisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('data_coleta', models.DateField(blank=True, null=True)),
                ('resultado_encrypted', models.TextField()),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('participacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dados', to='accounts.participacaopesquisa')),
            ],
        ),
    ]
