# Generated by Django 5.2.17 on 2026-09-16 21:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_dadopesquisa'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesquisa',
            name='pesquisadores',
            field=models.ManyToManyField(blank=True, limit_choices_to={'perfil': 'pesquisador'}, related_name='pesquisas_pesquisador', to=settings.AUTH_USER_MODEL),
        ),
    ]
