# Generated by Django 5.2.17 on 2026-08-23 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_aluno_alter_usuario_perfil_auditlog_consentimento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='dois_fatores_ativado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='secret_key',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
