# Generated by Django 5.2.17 on 2026-10-08 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_pesquisa_pesquisadores'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='hash_anterior',
            field=models.CharField(default='0000000000000000000000000000000000000000000000000000000000000000', editable=False, help_text='Hash do registro anterior, formando a cadeia.', max_length=64),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='hash_integridade',
            field=models.CharField(default=73245235425425349254, editable=False, help_text='Hash de integridade que inclui o hash_anterior.', max_length=64),
            preserve_default=False,
        ),
    ]
