# Generated by Django 5.2.17 on 2026-08-26 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_usuario_dois_fatores_ativado_usuario_secret_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='bloqueado_ate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tentativas_login',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ultimo_login_falhou',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
