# Generated by Django 5.2.17 on 2026-08-26 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_usuario_bloqueado_ate_usuario_tentativas_login_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='bloqueado_2fa_ate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tentativas_2fa',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
